**SELECTING DATA FROM TENSORS**

In [1]:
# INDEXING WITH PYTORCH

In [3]:
import torch

In [4]:
x=torch.arange(1,10).reshape(1,3,3)
x.shape

torch.Size([1, 3, 3])

In [5]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
# to get first number
x[:,0:1,0:1]

tensor([[[1]]])

In [9]:
#how to access 5 in the tensor
x[:,1:2,1:2]

tensor([[[5]]])

In [10]:
# to access 9 in the tensor
x[:,2:,2:]

tensor([[[9]]])

In [11]:
#lets index middle bracket middle dimension(dim=1)

In [15]:
x[0][0]

tensor([1, 2, 3])

alternatively

In [12]:
x[0,0]

tensor([1, 2, 3])

In [13]:
#lets index on the most inner bracket(last dimension)


In [14]:
x[0][0][0]

tensor(1)

In [17]:
# lets try
x[0][1][1]

tensor(5)

In [18]:
# how to get number 9
x[0][2][2]

tensor(9)

In [19]:
# Get all values of 0th and 6th dimensions but only index one and two

In [23]:
x[:,:,1]

tensor([[2, 5, 8]])

In [24]:
# get all values of the 0 th dimension but only the 1 index value of 1st and 2nd dimension

In [25]:
x[:,1,1]

tensor([5])

In [26]:
#Get index 0 of the 0 th and 1st dimension and all values of second dimensions

In [27]:
x[0,0,:]

tensor([1, 2, 3])

In [28]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
# index on x to return 9
x[0,2,2]

tensor(9)

In [30]:
# index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

**PYTORCH TENSORS AND NUMPY**
NUMPY IS A POPULAR SCIENTIFIC PYTHON NUMERICAL COMPUTING LIBRARY, AND BECAUSE OF THIS ,PYTORCH HAS FUNCTIONALITY TO INTERACT WITH IT
**Data in numpy, want in pytorch tensor->torch.from_numpy(ndarray)**
**pytorch tensor->numpy->torch.Tensor.numpy()

In [31]:
# numpy array to tensor
import torch
import numpy as np

In [32]:
array=np.arange(1.0,8.0)

In [38]:
tensor=torch.from_numpy(array.astype(np.float32))


In [40]:
array,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [35]:
# when converting from numpy->pytorch,pytorch reflects numpy's default datatype of float64,unless specified otherwise

In [41]:
# change value of array, what will this do to the tensor

In [42]:
array=array +1

In [43]:
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#but tensor value is not changed

In [44]:
#how to convert from tensor to numpy array

In [45]:
tensor=torch.ones(7)

In [46]:
numpy_tensor=tensor.numpy()

In [48]:
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [49]:
# change tensor what happens to numpy

In [50]:
tensor=tensor+1
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [51]:
# this doenot affect array

**PYTORCH REPRODUCIBILITY**

**trying to take random out of random** in short nueral networks "start with random numbers->tensor operations->update random numbers and try to make the better representation of data**

In [52]:
# random seed flavour randomness

In [ ]:
#creat two random tensors


In [53]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.3422, 0.3769, 0.0164, 0.3278],
        [0.5549, 0.2811, 0.7384, 0.3289],
        [0.0421, 0.5770, 0.0595, 0.4415]])
tensor([[0.9090, 0.6593, 0.4031, 0.6461],
        [0.1905, 0.6153, 0.1026, 0.7562],
        [0.6018, 0.9181, 0.1500, 0.0713]])


In [54]:
#lets make some random but reproducible seed

In [55]:
# set random seed

In [56]:
RANDOM_SEED=42

In [61]:
torch.manual_seed(RANDOM_SEED)

In [62]:
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

In [63]:
print(random_tensor_C)

print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [64]:
# THERE IS NOW FLAVOUR IN RANDOMNESS

In [65]:
# RUNNING TENSORS AND PYTORCH OBJECTS ON THE GPUS( AND MAKING FASTER COMPUTATIONS)

GPUs=faster computation on numbers

In [66]:
### 1. getting a GPU

**Easiest**=use google colab for a free GPU (options to upgrade as well)

**use your own GPU**=takes a little bit of set up and requires the investment of purchasing A GPU THERE IS LOTS OF OPTIONS

**Use cloud computing**=GCP,AWS,AZURE,these services allow you to rent computers on the cloud and access them

In [67]:
# for the above option 2 and 3 pytorch+GPU drivers (CUDA) takes a little bit of setting up,to do this refer to pytorch setup documentation

In [1]:
!nvidia-smi

Fri Jan 17 07:16:52 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
# check for GPU access with pytorch
import torch

In [6]:
torch.cuda.is_available()

True

In [7]:
# set_up device agnostic code

In [8]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [9]:
device

'cuda'

In [10]:
#count number of devices

In [11]:
torch.cuda.device_count()

1

FOR pytorch its capable of running compute on GPU or CPU , its a best practice to set up device agnostic code