In [ ]:
# PYTORCH FUNDAMENTALS

**PYTORCH FUNDAMENTALS**

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.5.1+cu121


In [4]:
## introduction to tensor
### creating tensor
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

**PyTorch tensors are created by using 'torch.Tensor()'**

**This is how to check for the number of dimensions**

In [5]:
scalar.ndim

0

**To check items in scalar**

In [7]:
scalar.item()

7

**Lets now talk about vectors,
Vectors has both magnitude and directions**

In [8]:
vector=torch.Tensor([7,7])
vector

tensor([7., 7.])

**to check the shape this is what we do**

In [9]:
vector.shape

torch.Size([2])

**MATRIX**


In [12]:
MATRIX= torch.Tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In matrix we use double square brackets

In [13]:
# To check number of dimensions
MATRIX.ndim

2

**Therefore matrix has 2 dimensions  and the value in each dimensions can be accessed**

In [14]:
MATRIX[0]

tensor([7., 8.])

Just simple as the above work

In [15]:
# this is how to determine shape of the matrix
MATRIX.shape

torch.Size([2, 2])

This is a 2x2 matrix

In [16]:
TENSOR= torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])

In [18]:
# to check the number of dimension
TENSOR.ndim

3

In [19]:
# this is how to check for the shape of the tensor
TENSOR.shape

torch.Size([1, 3, 3])

**TO access elements in the dimensions this is what we DO**

TENSOR[0]

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
# THIS MEANS THIS TENSOR IS  having one 3x3 matrix

**CREATING RANDOM TENSORS**

In [ ]:
# RANDOM TENSOR IS VERY IMPORTANT BECAUSE THE WAY THE NEURAL NETWORK LEARN IS THAT THEY START WITH TENSORS FULL OF RANDOM NUMBERS AND THEN ADJUST THE NUMBERS TO BETTER REPRESENT THE DATA

**Start with random numbers--look at data--update random numbers--look at the data update random numbers**

This is how to creat random tensor of shape 3 x 4

In [29]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5896, 0.8819, 0.7044, 0.4439],
        [0.2791, 0.5456, 0.7244, 0.1067],
        [0.6308, 0.8960, 0.4392, 0.1428]])

In [24]:
# creating random tensors in pytorch size(3,4)

This is how to creat two 3x2 matrix in pytorch

In [30]:
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.5623, 0.8714, 0.1978, 0.3430],
         [0.9679, 0.8339, 0.4537, 0.1020],
         [0.8922, 0.0672, 0.1220, 0.2168]],

        [[0.3370, 0.4456, 0.4515, 0.5186],
         [0.2606, 0.5162, 0.9512, 0.8203],
         [0.3448, 0.5748, 0.2234, 0.6814]]])

In [31]:
# to check the number of dimensions
random_tensor.ndim

3

**Creating a random tensor with similar shape to image tensor**

In [32]:
random_image_tensor=torch.rand(size=(224,224,3))# height width, color channel(R,G,B)

In [34]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [35]:
# we can also do this
torch.rand(size=(3,4))

tensor([[0.6748, 0.0092, 0.6999, 0.4009],
        [0.9145, 0.9625, 0.9079, 0.2420],
        [0.8175, 0.2122, 0.8248, 0.1754]])

**HOW TO CREAT  TENSORS ZEROS AND ONES**

```
# This is formatted as code
```



In [36]:
Zeros = torch.zeros(size=(3,4))
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

the above is how to creat tensors of zeros

In [37]:
# to creat tensors of all ones
ones=torch.ones(size=(3,4))

In [38]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**This is how to check for the data type of the tensor**

In [39]:
ones.dtype

torch.float32

the code is running on cpu

In [40]:
ones.device

device(type='cpu')

How to creat tensors and tensors like

In [41]:
# use torch.range()

In [47]:
one_ten=torch.arange(start=0,end=100,step=2)
one_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

**Creating tensors like**

In [53]:
#to convert the existing tensor into zeroes
ten_zeroes=torch.zeros_like(input=one_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [52]:
# to creat tensors ones_like to convert the existing tensors to all ones
ten_ones=torch.ones_like(input=one_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])

**TENSOR DATA TYPE**

In [55]:
float_32_tensor=torch.tensor([3.0,2.0,4.0],dtype=None)
float_32_tensor

tensor([3., 2., 4.])

In [56]:
float_32_tensor.dtype

torch.float32

In [57]:
# its by default float_32 but this can be changed lets take a look
float_32_tensor=torch.tensor([3.0,2.0,4.0],dtype=torch.float16)
float_32_tensor


tensor([3., 2., 4.], dtype=torch.float16)

***the data type thus can be easily changed***

TENSOR OPERATIONS CAN ONLY WORKS IN THE FOLLOWING CATEGORIES, MUST BE OF THE SAME DTYPE,RIGHT SHAPE, AND SAME DEVICE

In [58]:
# TO GET INFORMATION FROM A TENSOR
# we check on shape, dtype, device as the main parts to confirm