In [4]:
import numpy as np
import pandas as pd
import torch

In [5]:
some_tensor=torch.rand([3,4])

In [6]:
some_tensor.shape()

torch.Size([3, 4])

In [7]:
some_tensor.size()

torch.Size([3, 4])

Both shape and size can be used in a very similar way

**ADDITION**

In [8]:
# tensor operations

In [9]:
tensor=torch.rand([2,2])

In [10]:
add_tensor=tensor+10

tensor([[10.4025, 10.6232],
        [10.8918, 10.1458]])

**SUBTRACTION**

In [11]:
tensor_sub=tensor-10

In [12]:
tensor_sub

tensor([[-9.5975, -9.3768],
        [-9.1082, -9.8542]])

**MULTIPLICATION**

In [13]:
tensor_mult=tensor*5

In [14]:
tensor_mult

tensor([[2.0126, 3.1158],
        [4.4590, 0.7289]])

**LETS TRY INBUILT FUNCTIONS**

** ELEMENTWISE MULTIPLICATION**

In [16]:
tensor_1=torch.tensor([3,4])
tensor_2=torch.tensor([3,5])
tensor_1.mul(tensor_2)

tensor([ 9, 20])

In [18]:
torch.mul(tensor_1,tensor_2)

tensor([ 9, 20])

In [ ]:
# alternatively

In [17]:
tensor_1*tensor_2

tensor([ 9, 20])

Two main ways of performing multiplication in neural networks and deeplearning
* ELEMENTWISE MULTIPLICATION
* MATRIX MULTIPLICATON

**MATRIX MALTIPLICATION**

MATRIX MULTILICATION _THIS IS A MULTIPLYING A MATRIX BY ANOTHER MATRIX we need to do the the dot of rows and columns

In [22]:
tensor1=torch.rand([2,3])
tensor2=torch.rand([3,2])
torch.mm(tensor1,tensor2)

tensor([[0.3741, 1.1734],
        [0.4289, 1.5227]])

In [23]:
final=torch.matmul(tensor1,tensor2)

In [24]:
final

tensor([[0.3741, 1.1734],
        [0.4289, 1.5227]])

ALTERNATIVELY

In [25]:
tensor1@tensor2

tensor([[0.3741, 1.1734],
        [0.4289, 1.5227]])

In [27]:
%%time
value=0
for i in range(len(tensor1)):
  value += tensor1[i]*tensor1[i]
print(value)

tensor([1.6727, 0.1490, 1.6379])
CPU times: user 6.05 ms, sys: 0 ns, total: 6.05 ms
Wall time: 6.39 ms


In [29]:
%%time
torch.matmul(tensor1,tensor2)

CPU times: user 1.41 ms, sys: 36 µs, total: 1.45 ms
Wall time: 1.27 ms


tensor([[0.3741, 1.1734],
        [0.4289, 1.5227]])

The above showas that when we operates using torch, the operation takes short time than the other operations___for loop is slower

rules that must be attained   for the multiplication to occur
**1_The inner dimensions must match**
"3x2" @"3x2" this wont work
"2x3" @ "3x2" this one works since inner dimensions is the same

In [31]:
tens1=torch.rand(3,2)

In [32]:
tens2=torch.rand(3,2)
tens1@tens2 # this  dont works because inner dimensions are the same

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
tens3=torch.rand(3,2)
tens4=torch.rand(2,3)
tens3@tens4 # this now works because the inner dimensions are the same

tensor([[0.5495, 0.4961, 0.8732],
        [0.1658, 0.1495, 0.2630],
        [0.3565, 0.3143, 0.5481]])

**RULE2 The resulting matrix has the shape of the outer dimensions** eg "(2x3) @(3x2) the resulting matrix must have shape (2x2)

In [34]:
tensor3=torch.rand([2,3])
tensor4=torch.rand([3,2])
x=torch.mm(tensor3,tensor4) # shape must be (2x2)

In [35]:
x

tensor([[0.1795, 0.0858],
        [1.2808, 0.9120]])

In [36]:
x.shape

torch.Size([2, 2])

In [37]:
# the reultant matrix picks the outer dimensions as predicted
a=torch.rand([5,3])
b=torch.rand([3,4])
c=torch.mm(a,b)


In [38]:
c

tensor([[1.3259, 0.8422, 1.2629, 1.6935],
        [1.0088, 0.4467, 1.2736, 1.4006],
        [0.9339, 0.3082, 0.8601, 0.9286],
        [1.3331, 0.5637, 0.8870, 1.1300],
        [1.0519, 0.6007, 1.0342, 1.3154]])

In [39]:
# the resultant matrix should pick the outer dimension hence it will be (5x4)
c.shape

torch.Size([5, 4])

**Common errors in deep learning**

In [40]:
#shape errors torch.matmul is the same as torch.mm
tensor_A=torch.rand([3,2])
tensor_B=torch.rand([3,2])
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [42]:
# the code does not run because the inner dimensions does not match

**To fix this tensor shape error issues, we can manupulate the shape of one of our tensors using transpose**
Transpose switches the axes or dimensions of a given tensors

In [45]:
tensor_B=tensor_B.T

In [44]:
tensor_B

tensor([[0.7660, 0.5791],
        [0.6701, 0.0036],
        [0.3666, 0.6409]])

In [47]:
tensor_A=torch.rand([3,2])
tensor_B=torch.rand([3,2])
torch.mm(tensor_A,tensor_B.T)

tensor([[0.6710, 0.2393, 0.5000],
        [0.6222, 0.4839, 0.3609],
        [0.5536, 0.5558, 0.2719]])

In [48]:
#The above works when we transpose the tensor_B and thus the inner dimensions matches

**FINDING THE MEAN,MIN,MAX,SUM ETC OF TENSORS**

In [52]:
#creat tensor
x=torch.arange(22,100,3)
x

tensor([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73,
        76, 79, 82, 85, 88, 91, 94, 97])

In [53]:
#find minimum value
torch.min(x),x.min()

(tensor(22), tensor(22))

In [54]:
# finding maximum value of the tensor
torch.max(x),x.max()

(tensor(97), tensor(97))

In [55]:
#finding mean of the tensor
# we ensure that the tensor is of the same datatype
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(59.5000), tensor(59.5000))

In [56]:
# finding sum of the tensor
torch.sum(x),x.sum()

(tensor(1547), tensor(1547))

**FINDING POSITIONAL MEAN AND SUM ie AUGMAX,AUGMEAN RESPECTIVELY**

**This is how to find the index of mean and sum**

In [57]:
#find the position in tensor tha has the minimum value with argmin()--.reurns index position  where the minimum value occurs

In [58]:
x

tensor([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73,
        76, 79, 82, 85, 88, 91, 94, 97])

In [59]:
x.argmin()

tensor(0)

In [61]:
x[0]

tensor(22)

In [62]:
#find the position in tensor that has the minimum value with argmax()--.reurns index position  where the minimum value occurs

In [63]:
x

tensor([22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73,
        76, 79, 82, 85, 88, 91, 94, 97])

In [64]:
x.argmax()

tensor(25)

In [65]:
x[25]

tensor(97)

**RESHAPING VIEWING, STACKING ,SQUEEZING AND UNSQUEEZING**

**Reshaping**-reshapes an input tensor to a defined shape

**View**-return a view of an input tensor of certain shape but keep the same memory as the original tensor

**STACKING**-combines multiple tensors on top of each other (vstack) or side by side (hstack)
**Squeeze**-removes all "1" dimensions from the tensors

**Unsqueeze**-add a "1" dimensions to a target tensor
**Permute** -Return a view of input with dimensions permuted(swapped) in a certain way

In [66]:
#creat tensor
x=torch.arange(1.,10)

In [67]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
# add an extra dimensions
x_reshaped=x.reshape(3,3)


In [71]:
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [72]:
# the above is how we can have the shape of the tensor we need so long as number of elements match the tensor dimension in any arrangments
# change the view

**CHANGE THE VIEW**

In [75]:
z=x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [76]:
# changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [77]:
x

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])

In [82]:
# stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [5., 5., 5., 5., 5.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [83]:
# this is how to stack the tensors onto each other

In [89]:
p=torch.arange(0,100,5)

In [91]:
p.shape

torch.Size([20])

In [92]:
y=p.reshape(5,4)

In [93]:
y

tensor([[ 0,  5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55],
        [60, 65, 70, 75],
        [80, 85, 90, 95]])

In [99]:
z=torch.stack([y,y],dim=0)

In [100]:
z

tensor([[[ 0,  5, 10, 15],
         [20, 25, 30, 35],
         [40, 45, 50, 55],
         [60, 65, 70, 75],
         [80, 85, 90, 95]],

        [[ 0,  5, 10, 15],
         [20, 25, 30, 35],
         [40, 45, 50, 55],
         [60, 65, 70, 75],
         [80, 85, 90, 95]]])

In [101]:
#torch.squeeze()_remove all single dimensions


In [108]:
s=torch.rand(1,9)

In [109]:
s

tensor([[0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803, 0.0492]])

In [110]:
s.shape

torch.Size([1, 9])

In [111]:
s.squeeze().shape

torch.Size([9])

In [112]:
print(f"previous tensor:{s}")
print(f"previous shape:{s.shape}")

previous tensor:tensor([[0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803, 0.0492]])
previous shape:torch.Size([1, 9])


In [113]:
print(f"new tensor:{s.squeeze()}")
print(f"new shape:{s.squeeze().shape}")

new tensor:tensor([0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803, 0.0492])
new shape:torch.Size([9])


In [114]:
# torch.unsqueeze()--adds a single dimension to a target tensor at a specific dim(dimension)

In [115]:
print(f"previous target:{s}")
print(f"previous shape:{s.shape}")

previous target:tensor([[0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803, 0.0492]])
previous shape:torch.Size([1, 9])


In [118]:
print(f"new target:{s.unsqueeze(dim=0)}")
print(f"new shape:{s.unsqueeze(dim=1).shape}")


new target:tensor([[[0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803,
          0.0492]]])
new shape:torch.Size([1, 1, 9])


In [119]:
print(f"new target:{s.unsqueeze(dim=1)}")
print(f"new shape:{s.unsqueeze(dim=1).shape}")

new target:tensor([[[0.6161, 0.4958, 0.2237, 0.6828, 0.5475, 0.1794, 0.2004, 0.4803,
          0.0492]]])
new shape:torch.Size([1, 1, 9])


In [120]:
print(f"new target:{s.unsqueeze(dim=2)}")
print(f"new shape:{s.unsqueeze(dim=2).shape}")

new target:tensor([[[0.6161],
         [0.4958],
         [0.2237],
         [0.6828],
         [0.5475],
         [0.1794],
         [0.2004],
         [0.4803],
         [0.0492]]])
new shape:torch.Size([1, 9, 1])


In [122]:
print(f"new target:{s.unsqueeze(dim=4)}")
print(f"new shape:{s.unsqueeze(dim=4).shape}")

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 4)

In [123]:
#torch.permute_rearrange the dimensions of target tensors a specified order

In [124]:
x_original=torch.rand(size=(224,224,3))# height,width,color_channels

In [125]:
#permute the original tensor to rearrange the axis(or dim)order


In [126]:
x_permuted=x_original.permute(2,0,1)

In [127]:
x_permuted.shape

torch.Size([3, 224, 224])

In [128]:
x_original.shape

torch.Size([224, 224, 3])

In [129]:
print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


In [130]:
print(f"previous shape:{x_original}")
print(f"new shape:{x_permuted}")

previous shape:tensor([[[3.5491e-02, 3.9622e-01, 3.4610e-01],
         [1.5225e-01, 5.6633e-01, 7.3643e-01],
         [4.1947e-01, 9.6461e-01, 8.6284e-01],
         ...,
         [8.2718e-01, 6.0001e-01, 3.6585e-03],
         [5.4858e-02, 2.7656e-02, 4.4262e-01],
         [4.0981e-01, 4.4298e-01, 4.2427e-01]],

        [[4.5926e-01, 5.9897e-01, 8.9021e-01],
         [5.1508e-01, 1.4984e-01, 1.8943e-01],
         [1.7009e-01, 3.9785e-01, 2.3412e-01],
         ...,
         [6.4143e-01, 7.8307e-01, 4.1441e-01],
         [3.1382e-01, 7.7334e-01, 4.2781e-01],
         [2.5267e-01, 3.1020e-01, 5.9470e-01]],

        [[6.1778e-01, 6.5375e-01, 6.2840e-02],
         [6.9611e-01, 5.2347e-02, 3.9172e-01],
         [8.2668e-02, 5.6536e-01, 3.2306e-01],
         ...,
         [1.6511e-01, 3.3341e-01, 9.0119e-01],
         [2.8587e-01, 7.0239e-01, 2.4090e-01],
         [5.1610e-03, 5.5434e-01, 2.3244e-01]],

        ...,

        [[9.3172e-01, 8.2869e-01, 3.1966e-02],
         [5.7200e-01, 9.9077e-

In [131]:
x_original[0,0,0]=100
x_original[0,0,0],x_permuted[0,0,0]

(tensor(100.), tensor(100.))

In [ ]:
# indexing (selecting data from tensor)